# .github/workflows/build-to-acr.yml
name: Build & Deploy to ACA

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name totalsegacr

      - name: Build & push image
        run: |
          TAG=${{ github.sha }}
          az acr build \
            --registry totalsegacr \
            --image totalseg-api:${TAG} \
            .

      - name: Update Container App image
        run: |
          TAG=${{ github.sha }}
          az containerapp update \
            -g my-resource-group \
            -n totalseg-app \
            --image totalsegacr.azurecr.io/totalseg-api:${TAG}

      - name: Show latest revision
        run: az containerapp revision list -g my-resource-group -n totalseg-app -o table
